
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM tomcat
COPY C:/Users/ben10/OneDrive/Escritorio/MpResiduos/target/MpResiduos-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/MpResiduos-1.0-SNAPSHOT.war


